In [28]:
import pandas as pd
import seaborn as sns
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.metrics import accuracy_score, mean_absolute_error, mean_squared_error, classification_report, r2_score

In [2]:
df=pd.read_csv('energydata_complete.csv')
df.head()

,date,Appliances,lights,T1,RH_1,T2,RH_2,T3,RH_3,T4,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
0,2016-01-11 17:00:00,60,30,19.89,47.596667,19.2,44.790000,19.79,44.730000,19.000000,...,17.033333,45.53,6.600000,733.5,92.0,7.000000,63.000000,5.3,13.275433,13.275433
1,2016-01-11 17:10:00,60,30,19.89,46.693333,19.2,44.722500,19.79,44.790000,19.000000,...,17.066667,45.56,6.483333,733.6,92.0,6.666667,59.166667,5.2,18.606195,18.606195
2,2016-01-11 17:20:00,50,30,19.89,46.300000,19.2,44.626667,19.79,44.933333,18.926667,...,17.000000,45.50,6.366667,733.7,92.0,6.333333,55.333333,5.1,28.642668,28.642668
3,2016-01-11 17:30:00,50,40,19.89,46.066667,19.2,44.590000,19.79,45.000000,18.890000,...,17.000000,45.40,6.250000,733.8,92.0,6.000000,51.500000,5.0,45.410389,45.410389
4,2016-01-11 17:40:00,60,40,19.89,46.333333,19.2,44.530000,19.79,45.000000,18.890000,...,17.000000,45.40,6.133333,733.9,92.0,5.666667,47.666667,4.9,10.084097,10.084097

In [3]:
df.shape

(19735, 29)

In [101]:
df.isna().sum()

date           0
Appliances     0
lights         0
T1             0
RH_1           0
T2             0
RH_2           0
T3             0
RH_3           0
T4             0
RH_4           0
T5             0
RH_5           0
T6             0
RH_6           0
T7             0
RH_7           0
T8             0
RH_8           0
T9             0
RH_9           0
T_out          0
Press_mm_hg    0
RH_out         0
Windspeed      0
Visibility     0
Tdewpoint      0
rv1            0
rv2            0
dtype: int64

In [76]:
X=df['T2'].values.reshape(-1,1)
y=df['T6'].values.reshape(-1,1)

In [91]:
lr=LinearRegression()
lr.fit(X, y)
pred=lr.predict(X)

In [92]:
r2=r2_score(y, pred)
r2

0.6418990830855493

In [35]:
df_new=df.drop(['date', 'lights'], axis=1)

In [79]:
scaler=MinMaxScaler()
norm_df=scaler.fit_transform(df_new)
norm_df=pd.DataFrame(norm_df, columns=df_new.columns)
norm_df.head()

,Appliances,T1,RH_1,T2,RH_2,T3,RH_3,T4,RH_4,T5,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
0,0.046729,0.32735,0.566187,0.225345,0.684038,0.215188,0.746066,0.351351,0.764262,0.175506,...,0.223032,0.677290,0.372990,0.097674,0.894737,0.500000,0.953846,0.538462,0.265449,0.265449
1,0.046729,0.32735,0.541326,0.225345,0.682140,0.215188,0.748871,0.351351,0.782437,0.175506,...,0.226500,0.678532,0.369239,0.100000,0.894737,0.476190,0.894872,0.533937,0.372083,0.372083
2,0.037383,0.32735,0.530502,0.225345,0.679445,0.215188,0.755569,0.344745,0.778062,0.175506,...,0.219563,0.676049,0.365488,0.102326,0.894737,0.452381,0.835897,0.529412,0.572848,0.572848
3,0.037383,0.32735,0.524080,0.225345,0.678414,0.215188,0.758685,0.341441,0.770949,0.175506,...,0.219563,0.671909,0.361736,0.104651,0.894737,0.428571,0.776923,0.524887,0.908261,0.908261
4,0.046729,0.32735,0.531419,0.225345,0.676727,0.215188,0.758685,0.341441,0.762697,0.178691,...,0.219563,0.671909,0.357985,0.106977,0.894737,0.404762,0.717949,0.520362,0.201611,0.201611

In [80]:
x_new=norm_df.drop('Appliances', axis=1)
y_new=norm_df['Appliances']

In [81]:
X_train, X_test, y_train, y_test=train_test_split(x_new, y_new, test_size=0.3, random_state=42)

In [83]:
linreg=LinearRegression()
linreg.fit(X_train, y_train)
y_pred=linreg.predict(X_test)
MAE=mean_absolute_error(y_test, y_pred)
RMSS=np.sqrt(mean_squared_error(y_test, y_pred))

In [84]:
MAE

0.05013362397742957

In [85]:
RMSS

0.08751444947661711

In [102]:
residual_sum_square=np.sum(np.square(y_pred-y_test))
residual_sum_square

45.34762967266378

In [87]:
coef_of_determination=r2_score(y_test,y_pred)
coef_of_determination

0.14890246319303524

In [88]:
ridge=Ridge(0.4)
ridge.fit(X_train, y_train)
ridge_pred=ridge.predict(X_test)

In [89]:
mean_absolute_error(y_test, ridge_pred)

0.050087445840923825

In [90]:
lasso_reg=Lasso(alpha=0.001)
lasso_reg.fit(X_train, y_train)
lasso_pred=lasso_reg.predict(X_test)
np.sqrt(mean_squared_error(y_test, lasso_pred))

0.09358170467245137

In [107]:
def get_weights(model, fit, col_name):
    weights=pd.Series(model.coef_, fit.columns).sort_values()
    weights_df=pd.DataFrame(weights).reset_index()
    weights_df.columns=['Feautures', col_name]
    weights_df[col_name].round(2)
    return weights_df

In [104]:
model_weight=get_weights(linreg, X_train, 'model_weights')
ridge_weight=get_weights(ridge, X_train, 'ridge_weights')
lasso_weight=get_weights(lasso_reg, X_train, 'lasso_weights')

In [105]:
final1=pd.merge(model_weight, ridge_weight, on='Feautures')
final2=pd.merge(final1, lasso_weight, on='Feautures')

In [106]:
final2

      Feautures  model_weights  ridge_weights  lasso_weights
0          RH_2      -0.456698      -0.411071      -0.000000
1         T_out      -0.321860      -0.262172       0.000000
2            T2      -0.236178      -0.201397       0.000000
3            T9      -0.189941      -0.188916      -0.000000
4          RH_8      -0.157595      -0.156830      -0.000110
5        RH_out      -0.077671      -0.054724      -0.049557
6          RH_7      -0.044614      -0.045977      -0.000000
7          RH_9      -0.039800      -0.041367      -0.000000
8            T5      -0.015657      -0.019853      -0.000000
9            T1      -0.003281      -0.018406       0.000000
10          rv1       0.000770       0.000748      -0.000000
11          rv2       0.000770       0.000748      -0.000000
12  Press_mm_hg       0.006839       0.006584      -0.000000
13           T7       0.010319       0.010098      -0.000000
14   Visibility       0.012307       0.012076       0.000000
15         RH_5       0.016006       0.016152       0.000000
16         RH_4       0.026386       0.024579       0.000000
17           T4       0.028981       0.027384      -0.000000
18    Windspeed       0.029183       0.030268       0.002912
19         RH_6       0.038049       0.035519      -0.000000
20         RH_3       0.096048       0.095135       0.000000
21           T8       0.101995       0.101028       0.000000
22    Tdewpoint       0.117758       0.083128       0.000000
23           T6       0.236425       0.217292       0.000000
24           T3       0.290627       0.288087       0.000000
25         RH_1       0.553547       0.519525       0.017880